######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 4 15:00:20 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += declarative 

# Input
HEADERS += gameview.h
SOURCES += gameview.cpp qmljewels.cpp
